---
title: "Class Materials"
format: html
listing:
  - id: slides
    contents:
      - weeks/week_*.qmd
    type: table
    fields: [title, description, subtitle]
    field-display-names:
      title: "Week"
      description: "Dates"
      subtitle: "Topic"
    date-format: "MMMM DD, YYYY"
    sort: [filename]
    sort-ui: false
    filter-ui: false
editor: visual
---

Have questions? [Sign up for Krista's office hours](https://calendar.app.google/aYywwCLgS8XwKK7H9)!

## Materials

::: {#slides}
:::

## Homework

Homework will be due by 12:00 PM Eastern time on the Monday following a class.

## Capstone Project

Course participants will have several weeks to complete their capstone project. The capstone project will analyze a current funding formula issue in the participants' state, and will include the following:

-   An overview of the policy problem

-   Description of the 2-3 policy changes they are modeling

-   How they know if the policy options would be an improvement over current policy

-   Data they used to do their analysis

The participants can do their capstone in a Quarto document, PowerPoint deck, or a Word document. With that said, the capstone must include at least 5 data visualizations the participant did in R. The teaching team will host office hours to provide targeted support to course participants as they work on their capstone projects.
