---
title: "R Resources"
editor: visual
format: html
---

## R Questions? Check Out These Online Forums

-   [**Stack Overflow**](https://stackoverflow.com/questions): A public platform where developers can find and contribute answers to technical challenges, including R.
-   [**Posit Community**](https://forum.posit.co/): A community for all things Posit. This is the place for any questions about package development, particularly (but not exclusively) for any questions about devtools, roxygen2, testthat, and friends.

## R Packages

-   [**`tidyverse`**](https://www.tidyverse.org/packages/): The core tidyverse includes the packages that you're likely to use in everyday data analyses.
-   [**`ggplot2`**](https://ggplot2.tidyverse.org/): ggplot2 is a system for declaratively creating graphics, based on The Grammar of Graphics. You provide the data, tell ggplot2 how to map variables to aesthetics, what graphical primitives to use, and it takes care of the details.
-   [**`dplyr`**](https://dplyr.tidyverse.org/): dplyr is a grammar of data manipulation, providing a consistent set of verbs that help you solve the most common data manipulation challenges.
-   [**`readr`**](https://readr.tidyverse.org/): The goal of readr is to provide a fast and friendly way to read rectangular data from delimited files, such as comma-separated values (CSV) and tab-separated values (TSV). It is designed to parse many types of data found in the wild, while providing an informative problem report when parsing leads to unexpected results.
-   [**`viridis`**](https://sjmgarnier.github.io/viridis/articles/intro-to-viridis.html): Provides a series of color maps that are designed to improve graph readability for readers with common forms of color blindness and/or color vision deficiency.
-   [**`scales`**](https://scales.r-lib.org/): Provides the internal scaling infrastructure used by ggplot2, and gives you tools to override the default breaks, labels, transformations and palettes.
- [**`tidycensus`**](https://walker-data.com/census-r/an-introduction-to-tidycensus.html): Allows users to work with US Census Bureau data. It provides an easy and streamlined way to access and analyze demographic data from various census datasets, including the Decennial Census and the American Community Survey (ACS)

## R Cheat Sheets

- [**R Color Palettes**](https://r-charts.com/color-palettes/): A collection of 497 palettes from 16 popular R packages divided into continuous, discrete, and dynamic palettes. 
- [**R Keyboard Shortcuts**](https://support.posit.co/hc/en-us/articles/200711853-Keyboard-Shortcuts-in-the-RStudio-IDE): Keyboard Shortcuts in the RStudio IDE.

## Free PDF Versions of Books on R

-   [**Efficient R programming**](https://bookdown.org/csgillespie/efficientR/) **by Colin Gillespie and Robin Lovelace:** This hands-on book teaches novices and experienced R users how to write efficient R code. Drawing on years of experience teaching R courses, authors Colin Gillespie and Robin Lovelace provide practical advice on a range of topics---from optimizing the set-up of RStudio to leveraging C++---that make this book a useful addition to any R user's bookshelf.
-   [**R for Data Science**](https://r4ds.hadley.nz/) **by Hadley Wickham:** This book will teach you how to do data science with R: You'll learn how to get your data into R, get it into the most useful structure, transform it and visualize.
-   [**Analyzing US Census Data: Methods, Maps, and Models in R**](https://walker-data.com/census-r/index.html) **by Kyle Walker:** Census data is widely used in the United States across numerous research and applied fields, including education, business, journalism, and many others. Until recently, the process of working with US Census data has required the use of a wide array of web interfaces and software platforms to prepare, map, and present data products. The goal of this book is to illustrate the utility of the R programming language for handling these tasks, allowing Census data users to manage their projects in a single computing environment.
