---
title: "Modeling Local Share Policies and Builiding Quarto Presentations"
date: "August 5, 2024"
format:
  revealjs:
    chalkboard: true
execute:
  freeze: auto
  echo: false
---

## Agenda

-   Review: Local Share Policies
-   Modeling local share policies
-   Break
-   Building Quarto presentations
-   Overview of last class

# Review: Local Share Policies

## How Property Taxes Fund Schools

A large share of funding for public schools (44.9%) is generated by taxes at the local level. Property taxes are the most common source of local tax revenue for public schools in large part because they provide a stable revenue stream compared to taxes on sales or income. These taxes can be set by counties, towns, or school boards, depending on state policy.

Property taxes are typically collected based on two variables:

-   Assessed value of property
-   Property tax rate, sometimes called the "mill" rate.

::: callout
**How do property taxes produce education finance inequities?**

School districts generate revenue from the local property tax associated with property located within districts' geographic boundaries. When school districts have significantly different levels of property wealth producing those tax revenues compared to one another, a massive barrier to equitable educational finance results.
:::

::: aside
Source: [NCES](https://nces.ed.gov/programs/digest/d22/tables/dt22_235.10.asp)
:::

## Defining key property tax terms

**What does "assessed value of property" mean?**

The assessed value of a property is the dollar value used by a local government to determine how much a particular property is worth. The assessed value of a property may not always match the market value. Some local governments use an assessment rate to translate the market value of a property into taxable value.

**What is the "property tax rate" or "mill rate?**

The mill rate is the number of dollars per \$1,000 in assessed value that property owners will owe each year. The mill rate multiplied by assessed value equals local property tax bills.

In some instances, state policy directly shapes or limits property taxes. Some states include caps on how much mill rates can grow each year; other states limit the growth in the assessed values of properties over time.

## What is a state expected local share policy? {.smaller}

In most states, the education funding formula includes an expectation that the local school district will contribute some portion of the amount needed to fund education in that district. This expected local contribution is subtracted from the total amount calculated by the state to be necessary to educate the district's students, and the difference is the amount of state education funding the district will receive.The amount of the expected local contribution varies from district to district, and states base their expectations on several different factors.

-   **Property valuation:** Applies particular property tax rate to the total valuation of local, taxable property.
-   **Income/wealth:** Uses a formula or metric to assess local income or wealth.
-   **Other local receipts:** Considers what the district receives from local, non-property taxes.
-   **Share of costs:** Applies a set percentage to the total amount needed to fund education in that district.
-   **Historical levels:** Based on the amount of local revenue contributed to education in the past.

## Does your state have a local share expectation? {.smaller .scrollable}

| **State**      | **Description**                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|:------------|:-------------------------------------------------------|
| Arkansas       | Arkansas expects localities to contribute revenue to the funding of public schools. The amount each locality is expected to raise for its education costs is based on its property values and its revenue from other local sources: Each locality is expected to contribute \$25.00 for every \$1,000 of assessed local property wealth for the purpose of funding its school district, along with revenue from a variety of other sources, including local sales and use taxes. |
| Maryland       | Maryland expects school districts to contribute revenue to their public schools. The amount each district is expected to raise is based on a combination of its property values, its residents\' income, and a defined share of the base amount calculated by the state to be necessary to educate its students.                                                                                                                                                                 |
| Michigan       | Virginia expects school districts to contribute revenue to their public schools. The amount each district is expected to raise is based on a combination of its property values, its residents\' income and economic activity, and an estimate of its revenue from local sales tax receipts, adjusted to satisfy a statewide expected local contribution.                                                                                                                        |
| North Carolina | North Carolina does not expect districts to contribute revenue to their public schools\' instructional and operational expenses. However, facilities expenses generally are the responsibility of county governments.                                                                                                                                                                                                                                                            |
| Virginia       | Virginia expects school districts to contribute revenue to their public schools. The amount each district is expected to raise is based on a combination of its property values, its residents\' income and economic activity, and an estimate of its revenue from local sales tax receipts, adjusted to satisfy a statewide expected local contribution.                                                                                                                        |
| Washington     | Washington does not expect districts to contribute revenue to their public schools. However, school districts are permitted to impose taxes to generate supplemental revenue, such as for transportation.                                                                                                                                                                                                                                                                        |

Source: EdBuild, 2023

# Modeling Local Share Policies 

To model the expected local share funding, you need to have property value assessment data by district. Ideally, you'd also have the ACTUAL local property tax revenue so you can calculate if the state's local share expectation policy is accurately capturing how much local funding districts are really raising. 


# Class example: Modeling the current local share policy 

```{r}

#| echo: true
#| eval: false

# load in the data 
state_example_data <- read_csv("data/class_example_local_share_data.csv")


# Calculate the value of 1 mill -----

state_example_local_mill_data <- state_example_data |>
  # Calculate the value of mill using the assessed property value
  mutate(value_1_mill = assessed_value / 1000) |>
  # In the state example, the local mill expectation is 25 mills. Multiply the 
  # value of 1 mill by the current expectation to get the total EXPECTED funding
  # and then calculate the per-pupil value of 1 mill so we can see the distribution 
  mutate(value_25_mill = value_1_mill * 25,
         value_25_mill_pp = value_25_mill / total_enroll) |>
  # I removed an outlier district
  filter(value_25_mill_pp < 30000) |>
  # Calculate the actual pp 
  mutate(actual_local_pp = local_revenue / total_enroll) |>
  # Calculate the difference in the expected local funding and the ACTUAL local funding 
  mutate(actual_local_diff = local_revenue - value_25_mill,
         actual_local_diff_pp = actual_local_diff / total_enroll)



# Model the distribution of current funding on value of 25 mill pp -----
ggplot(state_example_local_mill_data, aes(x = value_25_mill_pp,
                             y = state_expected_local_pp, 
                             size = total_enroll,
                             color = direct_cert_pct, group = 1)) + 
  geom_point(alpha = .8) +
  scale_color_viridis(end = .8, direction = -1,
                      labels = scales::percent_format(accuracy = 1)) +
  scale_size_continuous(labels = scales::comma_format()) +
  scale_x_continuous(labels = scales::dollar_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::dollar_format(accuracy = 1),
                     limits = c(0, 12000)) +
  labs(x = "Value of 25 Mill Per-Pupil, 2019-20", 
       y = "Current State + Expected Local Share Per-Pupil Funding",
       title = "Current State + Expected Local Share Funding Compared to Per-Pupil Value of 25 Mills",
       size = "Enrollment", 
       color = "Economically Disadvanataged %") +
  theme_bw() +
  theme(text = element_text(family = "Avenir", size = 12),
        plot.caption = element_text(hjust = 0, size = 10)) 


# Plot difference between the actual current local per-pupil funding and the expected local share -----
ggplot(state_example_local_mill_data, aes(x = value_25_mill_pp,
                                          y = actual_local_diff_pp, 
                                          size = total_enroll,
                                          color = direct_cert_pct, group = 1)) + 
  geom_point(alpha = .8) +
  scale_color_viridis(end = .8, direction = -1,
                      labels = scales::percent_format(accuracy = 1)) +
  scale_size_continuous(labels = scales::comma_format()) +
  scale_x_continuous(labels = scales::dollar_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::dollar_format(accuracy = 1),
                     limits = c(0, 12000)) +
  labs(x = "Value of 25 Mill Per-Pupil, 2019-20", 
       y = "Difference Between Actual and Expected Local Per-Pupil Funding",
       title = "Per-Pupil Difference Between Actual and Expected Local Per-Pupil Funding",
       size = "Enrollment", 
       color = "Economically Disadvanataged %") +
  theme_bw() +
  theme(text = element_text(family = "Avenir", size = 12),
        plot.caption = element_text(hjust = 0, size = 10))


# Model actual pp funding on value of 25 mill pp -----
ggplot(state_example_local_mill_data, aes(x = value_25_mill_pp,
                                          y = actual_local_pp, 
                                          size = total_enroll,
                                          color = direct_cert_pct, group = 1)) + 
  geom_point(alpha = .8) +
  geom_abline() +
  scale_color_viridis(end = .8, direction = -1,
                      labels = scales::percent_format(accuracy = 1)) +
  scale_size_continuous(labels = scales::comma_format()) +
  scale_x_continuous(labels = scales::dollar_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::dollar_format(accuracy = 1),
                     limits = c(0, 12000)) +
  labs(x = "Value of 25 Mill Per-Pupil, 2019-20", 
       y = "Actual Local Per-Pupil Funding",
       title = "Actual Local Per-Pupil Compared to Per-Pupil Value of 25 Mills",
       size = "Enrollment", 
       color = "Economically Disadvanataged %") +
  theme_bw() +
  theme(text = element_text(family = "Avenir", size = 12),
        plot.caption = element_text(hjust = 0, size = 10))




```

# Class Example: Increasing Local Share Policy to 30 Mills

**Base on our calculations, the current local share policy does not account for $998,367,719 of local funding that is currently in the education system.** From our modeling, we know that we can raise the mill requirement to 30 mills and it would only require one district to have to raise more in local funding, but it would recognize 
















